### ISSUE TITLE
format error

### ISSUE THREAD

**Issue by TUsama** [Phylogeny/JEIEnchantmentInfo#2]
After deleting this template, please provide the following information:
* Forge Version: 31.2.31; 1.15.2
* JEI Enchantment Info version: 1.1.0

![剪贴板图片](https://user-images.githubusercontent.com/21279092/89296077-75ea1380-d694-11ea-9f5d-d874301c4495.jpg)
only protection disappears this "format error", that is so weird.

**Comment by Phylogeny** [comment]
This was the result of percent symbols not being properly escaped.
