### ISSUE TITLE
Curse compatibility with 1.16.5

### ISSUE THREAD

**Issue by jclendineng** [Phylogeny/JEIEnchantmentInfo#4]
Curse only allows this mod to be downloaded on 1.16.4, can you mark this as compatible with 1.16.5?

**Comment by Phylogeny** [comment]
I've barley done any MC modding in the past ~1.5 years (and literally nothing in little over a year), but I'm trying to get back into it. As late as it is, I figure it's better then nothing, so I just marked the v1.2.1 release accordingly.

I also just released a build that works with MC 1.17.1 through the latest of 1.18.2.
