### ISSUE TITLE
(Enhancement) "Enchantment Descriptions" compatibility

### ISSUE THREAD

**Issue by skyjay1** [Phylogeny/JEIEnchantmentInfo#5]
Suggestion:
Allow the enchantment description key to be in the format `"enchantment.[MOD_ID].[ENCHANTMENT_REGISTRY_NAME].desc"` as well as the current supported format of `.description`. This will allow any mod that has Enchantment Descriptions compatibility to automatically be compatible with JEI Enchantment Info.
I've suggested the same compatibility to DarkHax [here](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues/52).

**Comment by Phylogeny** [comment]
As I just wrote in the other issue, I've hardly done any MC modding in ~1.5 years (and none in a bit over 1 year), but I'm trying to get back into it. Hopefully this is better late than never. This feature is added in v1.3.0 for MC 1.15.2-1.16.5 and in v2.0.0 for MC 1.17.2-1.18.2.
